# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23847e96f02d1638f14c79eb76542adf3acb635802957e0549fe98c9f3401ac6aa38a8eb339ee5bfbb371e3fc2bfdaa0c25af008126a2408c1e27a7827167a4b

test:
  secret_key_base: 3803543e8817160d5f001f9eaef7ecdd5dc3a8b076c200f1f91021543325deaeed427bb0dfa91200a8807a532be3e55b17d24ba0bd0b822f8dc1685583c5317c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
